### ISSUE TITLE
Use `checkdecls`

### ISSUE THREAD

**Issue by fpvandoorn** [fpvandoorn/carleson#62]
https://github.com/PatrickMassot/checkdecls

**Comment by pitmonticone** [comment]
Here is the related CI step: 

```yml
      - name: Check declarations
        run: ~/.elan/bin/lake exe checkdecls blueprint/lean_decls
```

**Comment by fpvandoorn** [comment]
Please PR an addition. It would also require updating `lake-manifest`.

**Comment by pitmonticone** [comment]
> Please PR an addition. It would also require updating `lake-manifest`.

Done.
